export const calculators = [
  {
    id: "emi",
    title: "EMI Calculator",
    description: "Calculate monthly loan EMI",
    category: "Loan",
    path: "/emi",
  },
  {
    id: "sip",
    title: "SIP Calculator",
    description: "Estimate investment growth with SIP",
    category: "Investment",
    path: "/sip",
  },
  {
    id: "sip-step-up",
    title: "Step-Up SIP Calculator",
    description: "Grow savings with annual step-up contributions",
    category: "Investment",
    path: "/sip-step-up",
  },
  {
    id: "fd",
    title: "FD Calculator",
    description: "Calculate fixed deposit maturity value",
    category: "Savings",
    path: "/fd",
  },
  {
    id: "rd",
    title: "RD Calculator",
    description: "Estimate recurring deposit returns",
    category: "Savings",
    path: "/rd",
  },
  {
    id: "gst",
    title: "GST Calculator",
    description: "Add or remove GST from amounts",
    category: "Tax",
    path: "/gst",
  },
  {
    id: "maths",
    title: "Calculator",
    description: "A clean calculator for quick math operations",
    category: "Tools",
    path: "/maths",
  },
  {
    id: "simple-interest",
    title: "Simple Interest",
    description: "Calculate simple interest easily",
    category: "Savings",
    path: "/simple-interest",
  },
  {
    id: "lumpsum",
    title: "Lumpsum Calculator",
    description: "Estimate one-time investment maturity with compounding",
    category: "Investment",
    path: "/lumpsum",
  },
  {
    id: "swp",
    title: "SWP Calculator",
    description: "Simulate systematic withdrawals from a corpus",
    category: "Cashflow",
    path: "/swp",
  },
  {
    id: "retirement",
    title: "Retirement Corpus",
    description: "Project your retirement corpus using savings and monthly contributions",
    category: "Retirement",
    path: "/retirement",
  },
  {
    id: "cagr",
    title: "CAGR Calculator",
    description: "Calculate compound annual growth rate for investments",
    category: "Planning",
    path: "/cagr",
  },
  {
    id: "npv",
    title: "NPV Calculator",
    description: "Evaluate investment value with net present value analysis",
    category: "Analysis",
    path: "/npv",
  },
  {
    id: "irr",
    title: "IRR Calculator",
    description: "Calculate internal rate of return for cashflows",
    category: "Analysis",
    path: "/irr",
  },
  {
    id: "sip-vs-lumpsum",
    title: "SIP vs Lumpsum",
    description: "Compare SIP growth against a one-time investment",
    category: "Comparison",
    path: "/sip-vs-lumpsum",
  },
  {
    id: "inflation",
    title: "Inflation Calculator",
    description: "See how inflation affects future purchasing power",
    category: "Planning",
    path: "/inflation",
  },
  {
    id: "ppf",
    title: "PPF Calculator",
    description: "Estimate maturity value for recurring PPF deposits",
    category: "Savings",
    path: "/ppf",
  },
];